Promise
=========

Ten dokument opisuje, jak działa mechanizm Promes w EcmaScript 6 i nie tylko:

* Co to są promesy i do czego się ich używa?
* Łańcuchy promes (chaining),
* Niestandardowe promesy.

Zanim były promesy
-------------------

Rozważmy taki kawałek kodu:

    const request = require("request");
    request("https://some.host.org/url1.json", (err, data) => {
        let count = 3;
        const results = [];

        const checkIfDone = () => count-- > 0 || doSomethingWithResults(results);

        request("https://some.host.org/url2/"+data.subtype+".json", (err, data) => {
            result[0] = data;
            checkIfDone();
        });

        request("https://another.host.org/url-over-there-1/"+data.reference+".json", (err, data) => {
            request("https://another.host.org/url-over-there-2/"+data.reference+".json", (err, data) => {
                request("https://another.host.org/url-over-there-3/"+data.reference+".json", (err, data) => {
                    request("https://another.host.org/url-over-there-4/"+data.reference+".json", (err, data) => {
                        request("https://another.host.org/url-over-there-5/"+data.reference+".json", (err, data) => {
                            request("https://another.host.org/url-over-there-6/"+data.reference+".json", (err, data) => {
                                request("https://another.host.org/url-over-there-7/"+data.reference+".json", (err, data) => {
                                    result[1] = data;
                                    checkIfDone();
                                });
                            });
                        });
                    });
                });
            });
        });

        request("https://some.host.org/url3/"+data.subtype+".json", (err, data) => {
            result[2] = data;
            checkIfDone();
        });

    });

* W kodzie nic nie wykonuje się w oczekiwanej kolejności.
* Najbliższa czytelność w repozytorium obok.
* Koniec jest w środku i właściwie inaczej nie da się tego napisać.
* No i najważniejsze: JavaScriptowa choinka śmierci!

Promesy, znane od lat 70tych, występujące w wielu językach, zostały dodane do ES6 w celu rozwiązania tego problemu.

Jak to zmieniły Promesy?
--------------------------

    const request = require("request-promise");
    request("https://some.host.org/url1.json")
        .then(
            (data) => Promise.all([
                request("https://some.host.org/url2/"+data.subtype+".json"),
                request("https://another.host.org/url-over-there-1/"+data.reference+".json")
                    .then((data) => request("https://another.host.org/url-over-there-2/"+data.reference+".json"))
                    .then((data) => request("https://another.host.org/url-over-there-3/"+data.reference+".json"))
                    .then((data) => request("https://another.host.org/url-over-there-4/"+data.reference+".json"))
                    .then((data) => request("https://another.host.org/url-over-there-5/"+data.reference+".json"))
                    .then((data) => request("https://another.host.org/url-over-there-6/"+data.reference+".json"))
                    .then((data) => request("https://another.host.org/url-over-there-7/"+data.reference+".json")),
                request("https://some.host.org/url3/"+data.subtype+".json")
            ])
        )
        .then(
            doSomethingWithResults
        )
        .catch(
            err => logError(err)
        )

* Wszystko jest po kolei!
* Nie ma choinki śmierci!
* Czytelność jest już nieco lepsza.
* I jeszcze do tego mamy obsługę wszystkich błędów w jednej linii!

Jak stworzyć Promise
----------------------

Podstawowa wersja:

    const whenValuesFetchedAsPromised = new Promise((resolve, reject) => {
        asyncFetchValues((error, values) => {
            if (error instanceof Error)
                reject(error);
            else if (error)
                throw new Error("Something went wrong");
            else
                resolve(values);
        });
    });

Promise może być zakończony rozwiązaniem (resolve), albo odrzuceniem (reject). Jakikolwiek błąd w wykonywaniu Promise
będzie powodował to samo, co reject.

Nasz promise jest wykonywany, a my "planujemy" co z nim zrobimy:

    whenValuesFetchedAsPromised
        .then(values => saveValues(values))
        .catch(handleAnError);

Promesa i co potem?
---------------------

Potem? Then!

    whenSomeValueFetched
        .then(
            whenAllWentOk,
            whenSomethingFailed
        )

Pierwszy argument w then:

* Wywołany jeśli Promise zostanie rozwiązany,
* Otrzymuje wartość przekazaną do funkcji rozwiązania (resolve),
* Może zwrócić nową wartość, albo promesę nowej wartości.

 A jeśli się nie uda? Drugi agrument (opcjonalny):

* Wywołany kiedy Promise zostanie odrzucony,
* Otrzymuje wartość błędu, lub podaną do funkcji odrzucenia (reject)
* Może kolejną wartość, albo promesę

Then zawsze zwraca kolejną promesę (patrz [Chaining](#chaining)). Jeśli podacie dwa argumenty, nawet w wypadku błędu
promesa będzie uznana za rozwiązaną z wartością zwróconą przez drugą funkcję.

A co jeśli nie podamy drugiego argumentu then?

Zasadniczo musimy złapać wszystkie wyjątki - `node` będzie wysypywał błędy, a w nadchodzących wersjach będzie też
kończył działający program.

Możemy podać drugi argument w wywołaniu "catch", który zadziała tak samo.

Łapanie błędów:

    whenSomeValueFailsToFetch
        .catch(
            handleAnError
        )

To po co then i catch? Wyjaśnienie na końcu następnego punktu.

Chaining
----------

A co jeśli planujemy zrobić kilka rzeczy po kolei? Na przykład coś sobie dobrać?

    whenValuesFetchedAsPromised
        .then(values => asyncGetKeysForValues(values))
        .then(valuesWithKeys => asyncSaveValuesWithKeys(valuesWithKeys))
        .catch(handleAnError);

A co jeśli błąd wystąpi gdzieś po drodze?

    // Nic. Zostanie złapany przez pierwszy catch

A co jeśli już mamy wynik w kolejnym kroku?

    // Świetnie! Po prostu go zwracamy i działa to bez zmian:

    whenValuesFetchedAsPromised
        .then(values => {
            if (valuesWithKeys.length > 0) {
                return asyncGetKeysForValues(values); // Zwraca promesę
            }
            return [];  // nie zwraca promesy, następny then wykona się natychmiast
        })
        .then(valuesWithKeys => {
            if (valuesWithKeys.length > 0) {
                return asyncSaveValuesWithKeys(valuesWithKeys);
            }
        })
        .catch(handleAnError);

A co z "catch po drodze"?

    // Nic. Catch działa tak, że dowolna ilość wcześniejszych "then" zostanie złapana.

Operacje równoległe
---------------------

Promise.all - czyli po wszystkim:

    Promise.all([
            asyncFirstOperation,
            asyncSecondOperation
        ])
        .then(
            ([result1, result2]) => connectToDatabase(result1)
                .then(
                    (connection) => connection.saveData(result2
                )
        )
        .catch(
            handleAnError
        );

Promise.race - czyli która pierwsza:

    readOriginalFile(fileName)
        .then(
            () => Promise.race([
                asyncSaveToDBOne(file),
                asyncSaveToDBTwo(file)
            ])
        )
        .then(
            deleteOriginal     // jeśli tylko zapisze się w którejś bazie, możemy się pozbyć oryginały
        )
        .catch(
            handleAnError
        );
